### ISSUE TITLE
Cannot create migration - ch03

### ISSUE THREAD

**Issue by esseedev** [PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure#186]
When I try to create a migration I get
```Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type ''. The exception 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Co
debreaker.Data.SqlServer.GamesSqlServerContext]' while attempting to activate 'Codebreaker.Data.SqlServer.GamesSqlServerContext'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728```

Automated migrations from code working fine with sample files. I just can't create migration or update database by dotnet ef.
Tested on ch03 folder, on mac and windows.

**Comment by christiannagel** [comment]
Thanks @esseedev for reporting this! First, I thought you might have missed passing the startup project with this command, but this is a different issue. With the move of the EF Core context creation to the ApplicationServices class, the initialization is no longer found from `dotnet ef migrations`.
I'll add designer initialization later today to cover this scenario. Thanks!

**Comment by christiannagel** [comment]
Thanks @esseedev for reporting this! First, I thought you might have missed passing the startup project with this command, but this is a different issue. With the move of the EF Core context creation to the `ApplicationServices` class, the initialization is no longer found from `dotnet ef migrations`.
I'll add designer initialization later today.

**Comment by christiannagel** [comment]
I've created a design-time context factory class in the SQL Server library (only in debug mode) which allows you to create the migrations without referencing the startup project (more in the readme file of this chapter):

```bash
cd Codebreaker.Data.SqlServer
dotnet ef migrations add <Name> -- "server=(localdb)\mssqllocaldb;database=Test;trusted_connection=true"
```
