### ISSUE TITLE
Chapter 3 : remove hard-coded strings: "Cosmos" and "SqlServer"

### ISSUE THREAD

**Issue by Nieze-BenMansour** [PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure#199]
Remove hard-coded strings: "Cosmos" and "SqlServer" and replace them with public constants from a new class (for example: DbType ).

**Comment by christiannagel** [comment]
@Nieze-BenMansour, I was thinking about this as well - but this requires building another library, and using this library from the apphost and the service projects. Originally I had this in the shared library, but this is not meant to be used from the app host.
Thus, I didn't think it would be worthwhile to add the complexity to add a project just for these strings.
