### ISSUE TITLE
Unused parameter "gameType"

### ISSUE THREAD

**Issue by szv** [PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure#37]
The parameter ```gameType``` is unused.
https://github.com/PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure/blob/749c00b6add214a8a85299f15600624c79ddf4ab/ch02/Codebreaker.GameAPIs/Data/GamesMemoryRepository.cs#L35-L39

**Comment by christiannagel** [comment]
It's not just the parameter, the method is unused since introducing the GamesQuery parameter. This will be removed as part of the Aspire iteration.
